config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # list
  get 'tasks', to: 'tasks#index'

  # details
  get 'tasks/:id', to: 'tasks#show', as: :task

  # new
  get 'new', to: 'tasks#new', as: :new_task

  # create
  post 'tasks', to: 'tasks#create'

  #EDIT
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # update
  patch 'tasks/:id', to: 'tasks#update'
  # delete
  delete '/tasks/:id', to: 'tasks#destroy', as: :destroy_task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  # go into Task class and find object with parameter :id -> id
  def show
    @task = Task.find(params[:id])
  end
  # create a new task instance
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <%= simple_form_for(task) do |f| %>
        <%= f.input :title %>
        <%= f.input :details %>
        <%= f.input :completed %>
        <%= f.submit class: 'btn btn-primary w-100' %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>Here are all your tasks.</h1>
<br>
<ul style="list-style: none;">
  <% @tasks.each do |task| %>
    <% if task.completed %>
      <li><i class='fas fa-check-square'></i><%=link_to task.title , task_path(task.id)%>: <%= task.details%></li>
    <% else %>
        <li><i class='far fa-square'></i><%=link_to task.title , task_path(task.id)%>: <%= task.details%></li>
    <% end %>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>Here is your task. 👀</h1>
<br>
<%= @task.title %>: <%= @task.details %>
<br>
<br>
<p><%= link_to "Back to tasks" , tasks_path%></p>
<p><%= link_to "edit" , edit_task_path%></p>
<p><%= link_to "Destroy #{@task.title}", destroy_task_path(@task), method: :delete, data: {confirm: "Are you sure you want to destroy #{@task.title}"}  %></p>